sudo pacman -Syu --noconfirm \
    adobe-source-sans-fonts \
    adw-gtk-theme \
    bat \
    blueberry \
    btop \
    cliphist \
    cloc \
    ddcutil \
    dunst \
    fastfetch \
    fd \
    flatpak \
    fuzzel \
    fzf \
    gdm \
    git \
    gnome-font-viewer \
    grim \
    hypridle \
    hyprland \
    hyprpaper \
    hyprpicker \
    hyprpolkitagent \
    hyprsunset \
    kitty \
    lazygit \
    man-db \
    nautilus \
    neovim \
    network-manager-applet \
    nextcloud-client \
    npm \
    nwg-look \
    papirus-icon-theme \
    pavucontrol \
    ripgrep \
    ripgrep-all \
    slurp \
    stow \
    texlive-latex \
    tldr \
    trash-cli \
    tree-sitter-cli \
    ttf-jetbrains-mono-nerd \
    waybar \
    wireguard-tools \
    wl-clipboard \
    xdg-desktop-portal-hyprland \
    zoxide \
    zsh-autosuggestions \
    zsh-syntax-highlighting
