promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true

gui:
  showCommandLog: false
  nerdFontsVersion: "3"
  showNumstatInFilesView: true
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4

git:
  autoForwardBranches: allBranches

